/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include "stm32f103xx.h"
#include "stm32f103xx.gpio_driver.h"
#include <string.h>

#define	HIGH	1
#define LOW		0
#define	BOTTON_PRESSED	LOW
int main(void)
{
	GPIO_Handle_t GpioLed;
	GPIO_Handle_t GpioBtn;
	memset(&GpioLed,0,sizeof(GpioLed));
	memset(&GpioBtn,0,sizeof(GpioBtn));
	//cấu hình cho led gpio

	GpioLed.pGPIOx = GPIOC;
	GpioLed.GPIO_PinConfig.GPIO_PinModeAndSpeed = GPIO_MODE_OUT_SPEED_2MHZ;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	GpioLed.GPIO_PinConfig.GPIO_CRF =GPIO_CNF_GEOUT_PP;

	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&GpioLed);

	//cấu hình cho nut nhấn

	GpioBtn.pGPIOx = GPIOC;
	GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_5;
	GpioBtn.GPIO_PinConfig.GPIO_PinModeAndSpeed = GPIO_MODE_IN;
	GpioBtn.GPIO_PinConfig.GPIO_CRF = GPIO_CNF_IN_PUPD;
	GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PU;
	GpioBtn.GPIO_PinConfig.GPIO_PinIRQ_Trigger = GPIO_IRQ_FT;

	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&GpioBtn);

	// cấu hình Interrupt

	GPIO_IRQConfig(IRQ_NO_EXTI9_5, ENABLE);
	GPIO_IRQConfig(IRQ_NO_EXTI9_5, DISABLE);

	while(1);
	return 0;
}
void EXTI9_5_IRQHandler(void)
{
	GPIO_IRQHandling(GPIO_PIN_5);
	GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_13);
}
