/*
 * saolon.c
 *
 *  Created on: Oct 15, 2022
 *      Author: Metisai_02
 */


/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include "stm32f103xx.h"
#include "stm32f103xx.gpio_driver.h"

#define	HIGH	1
#define LOW		0
#define	BOTTON_PRESSED	LOW
int main(void)
{
	GPIO_Handle_t GpioLed;

	//cấu hình cho led gpio

	GpioLed.pGPIOx = GPIOC;
	GpioLed.GPIO_PinConfig.GPIO_PinModeAndSpeed = GPIO_MODE_OUT_SPEED_2MHZ;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	GpioLed.GPIO_PinConfig.GPIO_CRF =GPIO_CNF_GEOUT_PP;

	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&GpioLed);

	while(1)
	{
		GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_13);
	}
	return 0;
}
